//list of words to guess.
exports.newWord = {
  wordList:['LUMOS','AZKABAN','POLYJOICE POTION','TOM RIDDLE','GRINGOTTS','DEATHLY HALLOWS','EXPELLIARMUS','BASILISK','QUIDDITCH','INVISIBILITY CLOAK','HORCRUXES','ELDER WAND','ACCIO']

};